### ISSUE TITLE
Plugin not starting

### ISSUE THREAD

**Issue by Lavitz** [codelibs/gitbucket-fess-plugin#22]
I think this plugin stopped working in the gitbucket version 4.23.1
It did work in 4.23.0, but fess could not crawl file contents because some kind of problem in gitbucket api now resolved. However, the plugin does not start showing the following stack trace for reference:

`java.lang.NoSuchMethodError: gitbucket.core.util.SyntaxSugars$.using(Ljava/lang/Object;Lscala/Function1;Lscala/Function1;)Ljava/lang/Object;
org.codelibs.gitbucket.fess.service.FessSettingsService.$anonfun$loadFessSettings$1(FessSettingsService.scala:25)
gitbucket.core.util.SyntaxSugars$.defining(SyntaxSugars.scala:12)
org.codelibs.gitbucket.fess.service.FessSettingsService.loadFessSettings(FessSettingsService.scala:23)
org.codelibs.gitbucket.fess.service.FessSettingsService.loadFessSettings$(FessSettingsService.scala:22)
org.codelibs.gitbucket.fess.controller.FessSearchController.loadFessSettings(FessSearchController.scala:10)
org.codelibs.gitbucket.fess.controller.FessSearchControllerBase.$anonfun$$init$$1(FessSearchController.scala:46)
org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
gitbucket.core.controller.ControllerBase.org$scalatra$json$JsonSupport$$super$invoke(ControllerBase.scala:34)
org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:88)
org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:178)
org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:164)
gitbucket.core.controller.ControllerBase.withRouteMultiParams(ControllerBase.scala:34)
org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:82)
org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:81)
gitbucket.core.controller.ControllerBase.invoke(ControllerBase.scala:34)
org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
scala.Option.flatMap(Option.scala:171)
org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
scala.collection.immutable.Stream.flatMap(Stream.scala:486)
org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
gitbucket.core.controller.ControllerBase.runRoutes(ControllerBase.scala:34)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:74)
gitbucket.core.servlet.PluginControllerFilter.$anonfun$doFilter$2(PluginControllerFilter.scala:42)
gitbucket.core.servlet.PluginControllerFilter.$anonfun$doFilter$2$adapted(PluginControllerFilter.scala:35)
scala.collection.immutable.Stream.foreach(Stream.scala:530)
gitbucket.core.servlet.PluginControllerFilter.doFilter(PluginControllerFilter.scala:35)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
org.scalatra.ScalatraFilter.$anonfun$doNotFound$1(ScalatraFilter.scala:79)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$5(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:121)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$3(ScalatraBase.scala:172)
scala.Option.getOrElse(Option.scala:121)
org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:172)
org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
gitbucket.core.controller.ControllerBase.executeRoutes(ControllerBase.scala:34)
org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
gitbucket.core.controller.ControllerBase.withResponse(ControllerBase.scala:34)
org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
gitbucket.core.controller.ControllerBase.withRequestResponse(ControllerBase.scala:34)
org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
gitbucket.core.controller.ControllerBase.org$scalatra$servlet$ServletBase$$super$handle(ControllerBase.scala:34)
org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
gitbucket.core.controller.ControllerBase.org$scalatra$FlashMapSupport$$super$handle(ControllerBase.scala:34)
org.scalatra.FlashMapSupport.$anonfun$handle$1(FlashMap.scala:170)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
gitbucket.core.controller.ControllerBase.withRequest(ControllerBase.scala:34)
org.scalatra.FlashMapSupport.handle(FlashMap.scala:145)
org.scalatra.FlashMapSupport.handle$(FlashMap.scala:144)
gitbucket.core.controller.ControllerBase.handle(ControllerBase.scala:34)
org.scalatra.ScalatraFilter.$anonfun$doFilter$1(ScalatraFilter.scala:41)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
org.scalatra.ScalatraFilter.doFilter(ScalatraFilter.scala:41)
org.scalatra.ScalatraFilter.doFilter$(ScalatraFilter.scala:36)
gitbucket.core.controller.ControllerBase.doFilter(ControllerBase.scala:74)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1(TransactionFilter.scala:39)
gitbucket.core.servlet.TransactionFilter.$anonfun$doFilter$1$adapted(TransactionFilter.scala:30)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:207)
slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:207)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:200)
com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:207)
gitbucket.core.servlet.TransactionFilter.doFilter(TransactionFilter.scala:30)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
org.eclipse.jetty.server.Server.handle(Server.java:561)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
java.lang.Thread.run(Thread.java:745)`

**Comment by kw-udon** [comment]
Hi. Sorry for late response.
I pushed a commit https://github.com/codelibs/gitbucket-fess-plugin/commit/ddd186dacbfb4759baed9e99f2413578b0ef3f93 to support GitBucket 24.1.
I confirmed that this also works well with GitBucket in current master branch.
You can try this by cloning the repository and running `sbt package`.

---

@marevol Could you please release ver. 1.4.0? 
I think it is also good to wait for the release of GitBucket 25. (I guess it's comming soon)

**Comment by kw-udon** [comment]
We released ver. 1.4.0
